baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
enableRobotsTXT = 'true'

[taxonomies]
  tag = 'tags'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Writing'
pageRef = '/writing'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[params]
  [params.social]
    twitter = '@thetylerashley'
